#!/bin/bash
valeurs=("7" "8" "9" "10" "J" "Q" "K" "A")
couleurs=("♠" "♦" "♥" "♣")
#echo ${valeurs[$((RANDOM%${#valeurs[@]}))]} ${couleurs[$((RANDOM%${#couleurs[@]}))]}
nbval=${#valeurs[@]}
r1=$((RANDOM%nbval))
nbcol=${#couleurs[@]}
r2=$((RANDOM%nbcol))
echo ${valeurs[$r1]} ${couleurs[$r2]}
