#!/bin/bash

# main est un tableau de 5 cartes
main=()
# tant qu'il n'y a pas 5 cartes
while [ ${#main[@]} -lt 5 ] 
do
    #tire une carte aléatoirement (calea)
    calea=$(./carte)
    #par défaut on la garde
    garder=true
    #on va regarder toutes les cartes dans main
    #et les comparer à calea
    for c in "${main[@]}"
    do
        if [ "${c}" == "${calea}" ]
        then
            #si elle est présente dans main
            #on ne garde pas la carte
            garder=false
        fi
    done
    # si on garde on ajoute à main
    if [ "${garder}" == true ] 
    then
        main+=("$calea")
    fi
done 
echo ${main[@]}
